### ISSUE TITLE
Broken demo page after removing the ngObiba injection

### ISSUE THREAD

**Issue by ymarcon** [obiba/sf-obiba-selection-tree#2]
After 99611eaa9b651c14bcfdea0ea97efb87754de86d the [js error](http://errors.angularjs.org/1.6.9/$injector/unpr?p0=markedPr…ider%20%3C-%20marked%20%3C-%20sfObibaSelectionTreeController) when loading demo page is

```
Error: $injector:unpr
Unknown Provider

Unknown provider: markedProvider <- marked <- sfObibaSelectionTreeController
```

**Comment by meek0** [comment]
should be fixed in mica 5.0.2 release

**Comment by ymarcon** [comment]
It is not mica related, this is about **this module**'s demo page.

**Comment by meek0** [comment]
the DAR form loads in demo's public page. Issue I see in console is a warning wrt moment being deprecated
![image](https://user-images.githubusercontent.com/6180385/186409721-c0e96e56-81b1-4e2f-ad73-c0f4a8aca163.png)

**Comment by meek0** [comment]
UI of the widget is also an issue.

**Comment by ymarcon** [comment]
the module's demo page is broken:
![image](https://user-images.githubusercontent.com/2581149/186416808-4ce683ed-7085-4819-b15a-181f67cd2f31.png)
